extern GtkWidget *window;
extern GtkWidget *abutton;
extern GtkWidget *sbutton;
extern GtkWidget *cbutton;
extern GtkWidget *box;
extern GtkWidget *bgrid;
extern GtkWidget *bsgrid;
extern GtkWidget *notebook;
extern GtkWidget *shadow_page_box;
extern GtkWidget *shadow_page_label;
extern GtkWidget *shadow_page_enable_shadow_cb;
extern GtkWidget *shadow_page_enable_xinerama_crop_cb;
extern GtkWidget *shadow_page_spinnersandcolor_grid;
extern GtkWidget *shadow_page_blur_spinner;
extern GtkWidget *shadow_page_leftoffset_spinner;
extern GtkWidget *shadow_page_topoffset_spinner;
extern GtkWidget *shadow_page_translucency_spinner;
extern GtkWidget *shadow_page_shadow_color_button;
extern GtkWidget *shadow_page_bs_label;
extern GtkWidget *shadow_page_lo_label;
extern GtkWidget *shadow_page_to_label;
extern GtkWidget *shadow_page_ts_label;
extern GtkWidget *shadow_page_sc_label;
extern GtkAdjustment *shadow_page_bsa;
extern GtkAdjustment *shadow_page_losa;
extern GtkAdjustment *shadow_page_tosa;
extern GtkAdjustment *shadow_page_tsa;
extern GtkWidget *opacity_page_box;
extern GtkWidget *opacity_page_label;
extern GtkWidget *opacity_page_spinners_grid;
extern GtkWidget *opacity_page_inactive_spinner;
extern GtkWidget *opacity_page_active_spinner;
extern GtkWidget *opacity_page_frame_spinner;
extern GtkWidget *opacity_page_inactived_spinner;
extern GtkWidget *opacity_page_combo_spinner;
extern GtkWidget *opacity_page_dnd_spinner;
extern GtkWidget *opacity_page_dock_spinner;
extern GtkWidget *opacity_page_toolbar_spinner;
extern GtkWidget *opacity_page_tooltip_spinner;
extern GtkWidget *opacity_page_notification_spinner;
extern GtkWidget *opacity_page_menu_spinner;
extern GtkWidget *opacity_page_dmenu_spinner;
extern GtkWidget *opacity_page_pmenu_spinner;
extern GtkWidget *opacity_page_is_label;
extern GtkWidget *opacity_page_as_label;
extern GtkWidget *opacity_page_fs_label;
extern GtkWidget *opacity_page_ids_label;
extern GtkWidget *opacity_page_combos_label;
extern GtkWidget *opacity_page_dnds_label;
extern GtkWidget *opacity_page_docks_label;
extern GtkWidget *opacity_page_tbs_label;
extern GtkWidget *opacity_page_tts_label;
extern GtkWidget *opacity_page_notifs_label;
extern GtkWidget *opacity_page_ms_label;
extern GtkWidget *opacity_page_dms_label;
extern GtkWidget *opacity_page_pms_label;
extern GtkAdjustment *opacity_page_isa;
extern GtkAdjustment *opacity_page_asa;
extern GtkAdjustment *opacity_page_fsa;
extern GtkAdjustment *opacity_page_idsa;
extern GtkAdjustment *opacity_page_combosa;
extern GtkAdjustment *opacity_page_dndsa;
extern GtkAdjustment *opacity_page_docksa;
extern GtkAdjustment *opacity_page_tbsa;
extern GtkAdjustment *opacity_page_ttsa;
extern GtkAdjustment *opacity_page_notifsa;
extern GtkAdjustment *opacity_page_msa;
extern GtkAdjustment *opacity_page_dmsa;
extern GtkAdjustment *opacity_page_pmsa;
extern GtkWidget *fade_page_box;
extern GtkWidget *fade_page_label;
extern GtkWidget *fade_page_spinners_grid;
extern GtkWidget *fade_page_enable_fade_cb;
extern GtkWidget *fade_page_avoid_fading_on_oc_cb;
extern GtkWidget *fade_page_avoid_destroyed_argb_cb;
extern GtkWidget *fade_page_delta_spinner;
extern GtkWidget *fade_page_finsteps_spinner;
extern GtkWidget *fade_page_foutsteps_spinner;
extern GtkWidget *fade_page_delta_label;
extern GtkWidget *fade_page_finsteps_label;
extern GtkWidget *fade_page_foutsteps_label;
extern GtkAdjustment *fade_page_foutsteps_adj;
extern GtkAdjustment *fade_page_finsteps_adj;
extern GtkAdjustment *fade_page_delta_adj;
extern GdkRGBA shadow_color;

void show_error_dialog(char *message);
void create_fade_page();
void create_opacity_page();
void create_shadow_page();
void create_window_buttons();
void switch_page(GtkNotebook *self, GtkWidget *page, guint page_num, gpointer user_data);
void save_settings(GtkWidget *widget, gpointer data);
void show_about_dialog(GtkWidget *widget, gpointer data);
void save_fade_page();
void save_opacity_page();
void save_shadow_page();
void toggle_shadow_page(int value);
void toggle_fade_page(int value);
void create_window();
